# Generated by Django 3.1.7 on 2021-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.CharField(default='x', max_length=25),
            preserve_default=False,
        ),
    ]
