# Generated by Django 3.1.7 on 2021-04-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210423_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='rebbithole',
        ),
    ]
