# Generated by Django 3.1.7 on 2021-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210424_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
