# Generated by Django 3.1.7 on 2021-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20210505_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karma',
        ),
    ]
