# Generated by Django 3.1.7 on 2021-05-10 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_delete_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrebbithole',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
