# Generated by Django 3.1.7 on 2021-05-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_postrebbithole_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
