# Generated by Django 3.1.7 on 2021-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Karma',
        ),
    ]
